apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: telephone-secrets
  labels:
    app: phone-directory
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phone-directory
      component: backend
  template:
    metadata:
      labels:
        app: phone-directory
        component: backend
    spec:
      containers:
        - name: backend
          image: phone-directory-backend:25068
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SECRET_KEY
            - name: FLASK_DEBUG
              value: "false"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: telephone-secrets
spec:
  selector:
    app: phone-directory
    component: backend
  ports:
    - port: 5000
      targetPort: 5000
