apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: telephone-secrets
  labels:
    app: phone-directory
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phone-directory
      component: frontend
  template:
    metadata:
      labels:
        app: phone-directory
        component: frontend
    spec:
      containers:
        - name: frontend
          image: phone-directory-frontend:25068
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: telephone-secrets
spec:
  type: LoadBalancer
  selector:
    app: phone-directory
    component: frontend
  ports:
    - port: 80
      targetPort: 80
